// https://github.com/monero-project/monero/blob/8286f07b265d16a87b3fe3bb53e8d7bf37b5265a/src/rpc/core_rpc_server_error_codes.h#L63
const MONERO_RPC_ERROR_CODE = {
    WRONG_PARAM: -1,
    TOO_BIG_HEIGHT: -2,
    TOO_BIG_RESERVE_SIZE: -3,
    WRONG_WALLET_ADDRESS: -4,
    INTERNAL_ERROR: -5,
    WRONG_BLOCKBLOB: -6,
    BLOCK_NOT_ACCEPTED: -7,
    CORE_BUSY: -9,
    WRONG_BLOCKBLOB_SIZE: -10,
    UNSUPPORTED_RPC: -11,
    MINING_TO_SUBADDRESS: -12,
    REGTEST_REQUIRED: -13,
    PAYMENT_REQUIRED: -14,
    INVALID_CLIENT: -15,
    PAYMENT_TOO_LOW: -16,
    DUPLICATE_PAYMENT: -17,
    STALE_PAYMENT: -18,
    RESTRICTED: -19,
};

module.exports = { MONERO_RPC_ERROR_CODE };
